import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Button from "@/app/_components/Button";
import ButtonOut from "@/app/_components/SignoutBtn"";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-800 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="absolute flex items-center justify-center w-full h-[10%] bg-white">
            <Button />
        <ButtonOut />
        </nav>
        {children}
      </body>
    </html>
  );
}
